### ISSUE TITLE
Is it compatible with Redmine 3.4?

### ISSUE THREAD

**Issue by roman-yagodin** [mbideau/redmine_zquery#1]

**Comment by mbideau** [comment]
Hi,

It might, but I've not tested it.

I've planned on porting all my plugins and redmine customization on 3.4
at the begining of the next year.

Sorry, I've not much free time those days.

If you want to help, Pull Request are welcome by the way.

Cheers

Le 12/07/2018 à 10:13, Roman M. Yagodin a écrit :

**Comment by koren85** [comment]
Hi.
It work's fine at Redmine 3.4.7.

But don't work with plugin redmineup_tags(

**Comment by mbideau** [comment]
Hi @koren85 ,
Thanks for the feeback.

Good to know that it works for you in verison 3.4.x.

I've not upgraded my redmine version yet.
As soon as I done this and confirm that it works for my use case, I'll close this issue.

I don't use this plugin, so I don't know what's the trouble.

**Comment by mbideau** [comment]
I have no time to maintain this project.
See the thread in the Redmine's issues to get an updated version of this : https://www.redmine.org/issues/4939#note-50
