### ISSUE TITLE
redmine 4.xx support

### ISSUE THREAD

**Issue by hagaygo** [mbideau/redmine_zquery#3]
It seems plugin does not work with redmine 4.03 , any plans on supporting it ?

**Comment by mbideau** [comment]
Hi @hagaygo 

Thanks for your question.

I'm not the developer nor the maintainer of this code (it is just a copy-paste if I remember correctly), but if I have time I'll maintain it a little.

If've not done the migration to Redmine 3.4.x yet, so version 4.x is not on my roadmap for now.
If i migrate to Redmine 4.x it will be later on this year, like this summer. I've really not enough free time to work on this.
If you're a developper the code in short, so you might be able to patch it (Pull Request welcome).

Cheers

**Comment by ereisinger** [comment]
Pls see [http://www.redmine.org/issues/4939](http://www.redmine.org/issues/4939). This Redmine ticket is more up to date as this repo.
I've done an update of _query plugin for Redmine 4.x

**Comment by mbideau** [comment]
@ereisinger Thanks for your feedback and updating this redmine module.
I've updated the README to add a DEPRECATED notice and a link to the redmine ticket you mentionned.
When I'll make the switch to Redmine 4.x I'll close this repo.
I hereby close this ticket.
