### ISSUE TITLE
Compatible with Redmine 5

### ISSUE THREAD

**Issue by SinghNanak** [mbideau/redmine_zquery#4]

**Comment by SinghNanak** [comment]
@mbideau is there any way you could help me

**Comment by mbideau** [comment]
Hey @nanaksingh13 ,
I am sorry but I don't have the time to maintain this project.
May be it is working with the version 4, and for the version 5 I have no clue.
You could also ask the Redmine's forum to get some help.
See this thread where you might find a solution : https://www.redmine.org/issues/4939#note-50

I'll mark this project deprecated.

Good luck,
Best regards
